export const protocolLabels: Record<string, string> = {
  'openai-chat': 'OpenAI Chat Completions',
  'openai-responses': 'OpenAI Responses',
  anthropic: 'Anthropic Messages',
  gemini: 'Google Gemini',
  codex: 'Codex · ChatGPT',
  kimi: 'Kimi Code · 账号授权',
  minimax: 'MiniMax Code · 账号授权',
};
export const presets = [
  {
    name: 'OpenCode Go 订阅',
    protocol: 'openai-chat',
    baseUrl: 'https://opencode.ai/zen/go/v1',
    auth: 'api-key',
    models: [],
  },
  {
    name: '自定义服务',
    protocol: 'openai-chat',
    baseUrl: 'https://api.example.com/v1',
    auth: 'api-key',
    models: [],
  },
  {
    name: 'OpenAI API',
    protocol: 'openai-responses',
    baseUrl: 'https://api.openai.com/v1',
    auth: 'api-key',
    models: [],
  },
  {
    name: 'DeepSeek',
    protocol: 'openai-chat',
    baseUrl: 'https://api.deepseek.com/v1',
    auth: 'api-key',
    models: ['deepseek-chat', 'deepseek-reasoner'],
  },
  {
    name: '通义千问',
    protocol: 'openai-chat',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    auth: 'api-key',
    models: ['qwen-plus'],
  },
  {
    name: 'Kimi 开放平台',
    protocol: 'openai-chat',
    baseUrl: 'https://api.moonshot.cn/v1',
    auth: 'api-key',
    models: [],
  },
  {
    name: 'Kimi Code 套餐 Key',
    protocol: 'openai-chat',
    baseUrl: 'https://api.kimi.com/coding/v1',
    auth: 'api-key',
    models: ['kimi-for-coding'],
  },
  {
    name: 'MiniMax 国内 API / 套餐',
    protocol: 'anthropic',
    baseUrl: 'https://api.minimax.cn/anthropic/v1',
    auth: 'api-key',
    models: ['MiniMax-M3', 'MiniMax-M2.7', 'MiniMax-M2.5'],
  },
  {
    name: 'MiniMax 国际 API / 套餐',
    protocol: 'anthropic',
    baseUrl: 'https://api.minimax.io/anthropic/v1',
    auth: 'api-key',
    models: ['MiniMax-M3', 'MiniMax-M2.7', 'MiniMax-M2.5'],
  },
  {
    name: '智谱 GLM',
    protocol: 'openai-chat',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    auth: 'api-key',
    models: [],
  },
  {
    name: 'Anthropic',
    protocol: 'anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    auth: 'api-key',
    models: [],
  },
  {
    name: 'Google Gemini',
    protocol: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    auth: 'api-key',
    models: [],
  },
  {
    name: 'Ollama / 本地',
    protocol: 'openai-chat',
    baseUrl: 'http://127.0.0.1:11434/v1',
    auth: 'none',
    models: [],
  },
] as const;
